/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2015-11-16 19:10:01 UTC)
 * on 2016-01-03 at 00:51:16 UTC 
 * Modify at your own risk.
 */

package com.appspot.skoozi_959.skooziqna.model;

/**
 * Post that stores a question
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the skooziqna. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CoreModelsQuestionMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String content;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_urlsafe")
  private java.lang.String idUrlsafe;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double locationLat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double locationLon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("timestamp_unix") @com.google.api.client.json.JsonString
  private java.lang.Long timestampUnix;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContent() {
    return content;
  }

  /**
   * @param content content or {@code null} for none
   */
  public CoreModelsQuestionMessage setContent(java.lang.String content) {
    this.content = content;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdUrlsafe() {
    return idUrlsafe;
  }

  /**
   * @param idUrlsafe idUrlsafe or {@code null} for none
   */
  public CoreModelsQuestionMessage setIdUrlsafe(java.lang.String idUrlsafe) {
    this.idUrlsafe = idUrlsafe;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLocationLat() {
    return locationLat;
  }

  /**
   * @param locationLat locationLat or {@code null} for none
   */
  public CoreModelsQuestionMessage setLocationLat(java.lang.Double locationLat) {
    this.locationLat = locationLat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLocationLon() {
    return locationLon;
  }

  /**
   * @param locationLon locationLon or {@code null} for none
   */
  public CoreModelsQuestionMessage setLocationLon(java.lang.Double locationLon) {
    this.locationLon = locationLon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTimestampUnix() {
    return timestampUnix;
  }

  /**
   * @param timestampUnix timestampUnix or {@code null} for none
   */
  public CoreModelsQuestionMessage setTimestampUnix(java.lang.Long timestampUnix) {
    this.timestampUnix = timestampUnix;
    return this;
  }

  @Override
  public CoreModelsQuestionMessage set(String fieldName, Object value) {
    return (CoreModelsQuestionMessage) super.set(fieldName, value);
  }

  @Override
  public CoreModelsQuestionMessage clone() {
    return (CoreModelsQuestionMessage) super.clone();
  }

}
